[package]
name = "wireguard-gui"
version = "0.1.0"
edition = "2021"

[dependencies]
cidr = "0.2.3"
config-rs = "0.1.3"
nix = { version = "0.29.0", features = ["user"]}
relm4 = "0.8.1"
relm4-components = "0.8.1"
tar = "0.4.41"
tempfile = "3.10.1"
tokio = { version = "1.38.1", features = ["full"] }
